version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - broker
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  broker:
    driver: bridge